"""DFTTool — DFT计算工具 (VASP/QE接口)
输入文件生成、作业提交、结果解析
Developer: Westlake Singularity Contributors
"""

from dataclasses import dataclass, field
from typing import Optional

@dataclass
class DFTParams:
    """DFT计算参数"""
    # 结构
    lattice_vectors: list = field(default_factory=lambda: [[1,0,0],[0,1,0],[0,0,1]])
    atoms: list = field(default_factory=list)  # [(element, [x,y,z]), ...]
    
    # 计算
    functional: str = "PBE"
    kpoints: tuple = (8, 8, 1)
    encut_eV: float = 400.0
    ispin: int = 2  # 自旋极化
    lorbital: bool = True  # 原子轨道投影
    
    # 收敛
    ediff: float = 1e-6
    ediffg: float = -0.01
    nsw: int = 100
    ibrion: int = 2


class DFTTool:
    """DFT计算工具 — VASP/QE统一接口"""
    
    def __init__(self, code: str = "vasp"):
        self.code = code.lower()
        self.params = DFTParams()
        self._last_job_id: Optional[str] = None
    
    def generate_incar(self, params: DFTParams = None) -> str:
        """生成VASP INCAR文件"""
        p = params or self.params
        return f"""! VASP INCAR — generated by Westlake Singularity
SYSTEM = WestlakeSingularity_DFT
ENCUT = {p.encut_eV:.1f}
ISMEAR = 0
SIGMA = 0.05
EDIFF = {p.ediff:.1e}
EDIFFG = {p.ediffg:.2f}
NSW = {p.nsw}
IBRION = {p.ibrion}
ISIF = 3
ISPIN = {p.ispin}
LORBIT = {11 if p.lorbital else 10}
LREAL = Auto
PREC = Accurate
"""
    
    def generate_poscar(self, params: DFTParams = None) -> str:
        """生成VASP POSCAR文件"""
        p = params or self.params
        lines = ["WestlakeSingularity_DFT", "1.0"]
        for v in p.lattice_vectors:
            lines.append(f"  {v[0]:.8f}  {v[1]:.8f}  {v[2]:.8f}")
        
        elements = {}
        for el, _ in p.atoms:
            elements[el] = elements.get(el, 0) + 1
        
        lines.append("  ".join(elements.keys()))
        lines.append("  ".join(str(n) for n in elements.values()))
        lines.append("Cartesian")
        
        for el, pos in p.atoms:
            lines.append(f"  {pos[0]:.8f}  {pos[1]:.8f}  {pos[2]:.8f}")
        
        return "\n".join(lines)
    
    def generate_kpoints(self, params: DFTParams = None) -> str:
        """生成KPOINTS文件"""
        p = params or self.params
        return f"""Automatic mesh
0
Monkhorst-Pack
{p.kpoints[0]} {p.kpoints[1]} {p.kpoints[2]}
0.0 0.0 0.0
"""
    
    def parse_outcar(self, outcar_content: str) -> dict:
        """解析VASP OUTCAR — 提取能带、能量等"""
        result = {"total_energy_eV": None, "band_gap_eV": None, "magnetic_moment": None}
        
        for line in outcar_content.split("\n"):
            if "FREE ENERGIE OF THE ION-ELECTRON SYSTEM" in line:
                try:
                    result["total_energy_eV"] = float(line.split()[-2])
                except (ValueError, IndexError):
                    pass
            if "number of electron" in line and "magnetization" in line:
                try:
                    result["magnetic_moment"] = float(line.split()[-1])
                except (ValueError, IndexError):
                    pass
        
        return result
    
    def create_slurm_script(self, job_name: str, ncores: int = 64, 
                            walltime: str = "24:00:00") -> str:
        """生成Slurm作业脚本"""
        return f"""#!/bin/bash
#SBATCH --job-name={job_name}
#SBATCH --nodes=1
#SBATCH --ntasks={ncores}
#SBATCH --time={walltime}
#SBATCH --partition=gpu
#SBATCH --output={job_name}_%j.out

module load vasp/6.4.3

mpirun -np {ncores} vasp_std
"""
    
    def estimate_resources(self, n_atoms: int, encut: float = 400) -> dict:
        """估算计算资源（启发式）"""
        return {
            "ncores_recommended": max(8, n_atoms // 2),
            "memory_gb": max(2, n_atoms * encut / 100),
            "walltime_h": max(1, n_atoms / 5),
            "cost_core_hours": n_atoms * encut / 50,
        }
